# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: kz-backend-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-2 #London
  profile: serverless
  environment:
      DB_HOST: ${file(./db.js):DB_HOST}
      DB_USER: ${file(./db.js):DB_USER}
      DB_PASSWORD: ${file(./db.js):DB_PASSWORD}
functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  viewPlan:
    handler: activityPlanHandler.viewPlan #handler.functionName GET
    events:
      - http:
          path: /viewPlan/{id}
          method: GET
  createPlan:
    handler: activityPlanHandler.createPlan #handler.functionName POST
    events:
      - http:
          path: /createPlan
          method: POST
  updatePlan:
    handler: activityPlanHandler.updatePlan #handler.functionName PUT
    events:
      - http:
          path: /updatePlan/{id}
          method: PUT
  cancelPlan:
    handler: activityPlanHandler.cancelPlan #handler.functionName DELETE
    events:
      - http:
          path: /cancelPlan/{id}
          method: DELETE